#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDRiver
#    password: oracle
#    url: jdbc:oracle:thin:@localhost:1521/XE
#    username: nabin123
#  jpa:
#    properties:
#      hibernate:
#      format_sql: true
#      show_sql: true
#  
#  mvc:
#    view:
#      prefix: /views/
#      suffix: .jsp
#server:
#  port: 8080
#  servlet:
#    context-path: /PhoneBook
