#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDRiver
#    password: oracle
#    url: jdbc:oracle:thin:@localhost:1521/XE
#    username: nabin123


spring:
  h2:
    console:
      enabled: true
      path: /h2 
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
      format_sql: true
      show_sql: true
  
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
server:
  port: 8083
  servlet:
    context-path: /PhoneBook
